export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_REQUESTORS_SUCCESS = 'LOAD_REQUESTORS_SUCCESS';

export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
